sc delete "AxInstSV"
sc delete "AJRouter"
sc config "BDESVC" start= "disabled"
sc delete "wbengine"
sc delete "CDPUserSvc"
sc delete "CDPSvc"
sc delete "DiagTrack"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\PimIndexMaintenanceSvc" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "DsSvc"
sc config "DPS" start= "disabled"
sc config "WdiServiceHost" start= "disabled"
sc config "WdiSystemHost" start= "disabled"
sc delete "dmwappushservice"
sc delete "MapsBroker"
sc delete "fhsvc"
sc delete "lfsvc"
sc delete "HomeGroupListener"
sc delete "HomeGroupProvider"
sc delete "HvHost"
sc delete "vmickvpexchange"
sc delete "vmicguestinterface"
sc delete "vmicshutdown"
sc delete "vmicheartbeat"
sc delete "vmicvmsession"
sc delete "vmicrdv"
sc delete "vmictimesync"
sc delete "vmicvss"
sc delete "irmon"
sc delete "MessagingService"
sc delete "diagnosticshub.standardcollector.service"
sc delete "wlidsvc"
sc delete "swprv"
sc delete "smphost"
sc config "SmsRouter" start= "disabled"
sc delete "NcbService"
sc delete "PNRPsvc"
sc delete "p2psvc"
sc delete "p2pimsvc"
sc delete "PerfHost"
sc delete "pla"
sc delete "PhoneSvc"
sc delete "PNRPAutoReg"
sc delete "wercplsupport"
sc delete "SessionEnv"
sc delete "TermService"
sc delete "UmRdpService"
sc delete "RemoteRegistry"
sc delete "RetailDemo"
sc delete "wscsvc"
sc delete "SensorDataService"
sc delete "SensrSvc"
sc delete "SensorService"
sc delete "OneSyncSvc"
sc delete "TapiSrv"
sc delete "TabletInputService"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\UserDataSvc" /v "Start" /t "REG_DWORD" /d "4" /f
reg add "HKLM\SYSTEM\CurrentControlSet\Services\UnistoreSvc" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "VSS"
sc delete "WalletService"
sc delete "SDRSVC"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WdNisSvc" /v "Start" /t "REG_DWORD" /d "4" /f
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WinDefend" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "WEPHOSTSVC"
sc delete "WerSvc"
sc delete "wisvc"
sc delete "icssvc"
sc delete "Ndu"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\WpnUserService" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "WinRM"
sc delete "WSearch"
sc delete "XblAuthManager"
sc delete "XblGameSave"
sc delete "XboxNetApiSvc"
sc delete "WbioSrvc"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\xbgm" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "XboxGipSvc"
sc delete "spectrum"
sc delete "wisvc"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\DevicesFlowUserSvc" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "SEMgrSvc"
sc delete "NaturalAuthentication"
sc delete "WpnService"
sc delete "cplspcon"
sc delete "cphs"
reg add "HKLM\SYSTEM\CurrentControlSet\Services\Sense" /v "Start" /t "REG_DWORD" /d "4" /f
sc delete "DcpSvc"
sc delete "iaStorAfsService"
reg add "HKLM\SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\AutoLogger-Diagtrack-Listener" /v "Start" /t REG_DWORD /d "4" /f
reg add "HKLM\SYSTEM\ControlSet001\Control\WMI\AutoLogger\AutoLogger-Diagtrack-Listener" /v "Start" /t REG_DWORD /d "4" /f
reg add "HKLM\SYSTEM\CurrentControlSet\Services\SecurityHealthService" /v "Start" /t "REG_DWORD" /d "4" /f