install_wim_tweak.exe /o /c "Microsoft-OneCore-ApplicationModel-Sync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-DeviceSync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-EnterpriseClientSync" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-ShareMedia" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Telnet" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Serial" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-SenseClient" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-RDC" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Proximity" /r
install_wim_tweak.exe /o /c "Microsoft-Windows-Printing-PrintToPDFServices" /r